#!/usr/bin/env python3
"""Generate CATALOG.md from .fork/catalog.yaml.

    python3 scripts/generate-catalog.py           # rewrite CATALOG.md
    python3 scripts/generate-catalog.py --check   # exit 1 if CATALOG.md is stale

Fails closed: an unreadable catalog, an unknown domain, audience or status, a duplicate
skill name, or any mismatch between the catalog and the skills on disk is an
error, not a silently smaller table. Needs `pyyaml`, like skillcheck.py.
"""
import os
import sys

import yaml

HEADER = (
    "<!-- Generated by scripts/generate-catalog.py from .fork/catalog.yaml. "
    "Do not hand-edit: your changes will be overwritten. -->"
)


def die(msg):
    print(f"generate-catalog: {msg}", file=sys.stderr)
    sys.exit(1)


def find_skills_on_disk(repo):
    """Every skill directory under skills/ — list-skills.sh, scoped to the tree.

    (list-skills.sh searches the whole repo, so it also reports the gitignored
    isolated_test_workspace/ copy the harness makes. That copy is not a skill.)
    """
    found = set()
    root = os.path.join(repo, "skills")
    if not os.path.isdir(root):
        die("no skills/ directory — run from the repo root")
    for dirpath, _dirnames, filenames in os.walk(root):
        if "SKILL.md" in filenames:
            found.add(os.path.relpath(dirpath, repo))
    if not found:
        die("found no skills on disk")
    return found


def load_catalog(repo):
    path = os.path.join(repo, ".fork", "catalog.yaml")
    try:
        with open(path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except FileNotFoundError:
        die(f"{path} not found")
    except yaml.YAMLError as exc:
        die(f"{path} is not valid YAML: {exc}")
    if not isinstance(data, dict) or not isinstance(data.get("skills"), list):
        die(f"{path} must be a mapping with a `skills` list")
    return data


def validate(repo, catalog):
    domains = catalog.get("domains") or []
    audiences = catalog.get("audiences") or []
    if not domains or not audiences:
        die("catalog.yaml must declare `domains` and `audiences`")

    errors = []
    seen_names = {}
    entries = []
    for i, entry in enumerate(catalog["skills"]):
        where = entry.get("name") or f"skills[{i}]"
        for field in ("name", "path", "origin", "domain", "audience", "owner"):
            if not entry.get(field):
                errors.append(f"{where}: missing `{field}`")
        if errors and errors[-1].startswith(f"{where}: missing"):
            continue
        if entry["origin"] not in ("upstream", "fork"):
            errors.append(f"{where}: origin must be `upstream` or `fork`")
        if entry["domain"] not in domains:
            errors.append(f"{where}: domain `{entry['domain']}` not in `domains`")
        if entry.get("status") not in (None, "beta"):
            errors.append(f"{where}: status must be `beta` or absent")
        if not isinstance(entry["audience"], list):
            errors.append(f"{where}: audience must be a list")
        else:
            for role in entry["audience"]:
                if role not in audiences:
                    errors.append(f"{where}: audience `{role}` not in `audiences`")
        if entry["name"] in seen_names:
            errors.append(
                f"{where}: duplicate skill name — also {seen_names[entry['name']]}"
            )
        seen_names[entry["name"]] = entry["path"]
        if os.path.basename(entry["path"]) != entry["name"]:
            errors.append(f"{where}: name must be the directory basename of `path`")
        entries.append(entry)

    on_disk = find_skills_on_disk(repo)
    catalogued = {e["path"] for e in entries}
    for path in sorted(catalogued - on_disk):
        errors.append(f"catalogued but not on disk: {path}")
    for path in sorted(on_disk - catalogued):
        errors.append(f"on disk but missing from catalog.yaml: {path}")

    if errors:
        for err in errors:
            print(f"generate-catalog: {err}", file=sys.stderr)
        sys.exit(1)
    return entries, domains


def render(entries, domains):
    order = {d: i for i, d in enumerate(domains)}
    rows = sorted(entries, key=lambda e: (order[e["domain"]], e["name"]))
    upstream = sum(1 for e in rows if e["origin"] == "upstream")
    fork = len(rows) - upstream

    out = [
        HEADER,
        "",
        "# Skill catalog",
        "",
        f"Every skill in this repo: {len(rows)} total — {upstream} upstream, "
        f"{fork} fork-authored.",
        "",
        "`Origin` says who owns the bytes (`upstream` = "
        "[mattpocock/skills](https://github.com/mattpocock/skills), which may "
        "rewrite them in any sync; `fork` = this team). `Audience` is who the "
        "skill is for — a skill can serve several roles. A skill marked _(beta)_ is not promoted: no "
        "docs page, and not listed in the top-level README. Edit "
        "[.fork/catalog.yaml](.fork/catalog.yaml) and regenerate; never edit "
        "this file.",
        "",
        "| Skill | Origin | Domain | Audience | Owner |",
        "|---|---|---|---|---|",
    ]
    for e in rows:
        link = f"[{e['name']}]({e['path']}/SKILL.md)"
        if e.get("status") == "beta":
            link += " _(beta)_"
        audience = ", ".join(e["audience"])
        out.append(
            f"| {link} | {e['origin']} | {e['domain']} | {audience} | {e['owner']} |"
        )
    out.append("")
    return "\n".join(out)


def main():
    args = sys.argv[1:]
    check = "--check" in args
    positional = [a for a in args if not a.startswith("-")]
    repo = positional[0] if positional else "."
    unknown = [a for a in args if a.startswith("-") and a != "--check"]
    if unknown:
        die(f"unknown option(s): {' '.join(unknown)}")

    catalog = load_catalog(repo)
    entries, domains = validate(repo, catalog)
    rendered = render(entries, domains)

    target = os.path.join(repo, "CATALOG.md")
    current = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as fh:
            current = fh.read()

    if check:
        if current != rendered:
            die("CATALOG.md is stale — run `python3 scripts/generate-catalog.py`")
        print(f"CATALOG.md is up to date ({len(entries)} skills)")
        return

    if current == rendered:
        print(f"CATALOG.md unchanged ({len(entries)} skills)")
        return
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"CATALOG.md written ({len(entries)} skills)")


if __name__ == "__main__":
    main()
