#!/usr/bin/env python3
"""Generate .claude-plugin/marketplace.json from .fork/catalog.yaml.

    python3 scripts/generate-marketplace.py           # rewrite the manifest
    python3 scripts/generate-marketplace.py --check   # exit 1 if it is stale

This file exists for ONE reason: the skills.sh installer
(https://github.com/vercel-labs/skills) groups its interactive picker — with a
per-group "select all" row — only from `.claude-plugin/marketplace.json`. It
reads `plugins[].name` and `plugins[].skills[]` and nothing else. It is picker
metadata, NOT an install route: this fork ships via skills.sh only, and
`forkcheck.py`'s plugin-dir-marketplace-only rule keeps `plugin.json` out so
the plugin route stays closed. See .agents/adr/0002-ship-as-a-claude-code-plugin.md.

Group naming: an upstream bucket keeps its name (`engineering`); a fork domain
is prefixed (`mobile` -> `team-mobile`). The installer renders a name by
splitting on `-` and capitalising, so `team-mobile` shows as "Team Mobile".
Group order is not ours to choose — the installer sorts alphabetically.

Unshipped buckets (`misc`, `in-progress`, `deprecated`) are deliberately left
out. The installer pools every skill it cannot find in a group under a
hardcoded "Other" heading, which is an accurate label for them.

Fails closed, like generate-catalog.py: an unreadable catalog, an unknown
domain, or a manifest path with no SKILL.md behind it is an error, not a
silently smaller manifest. Needs `pyyaml`.
"""
import json
import os
import sys

import yaml

# Buckets upstream owns. Everything else in the catalog's `domains` list is a
# fork capability domain and lives under skills/team/.
UPSTREAM_BUCKETS = ("engineering", "productivity", "misc", "in-progress", "deprecated")

# Buckets we do not offer in the installer. `misc` and `in-progress` are
# upstream's deliberate published output, so they are not hidden — they fall to
# the installer's "Other" group. `deprecated` is retired work, and
# `in-development` is the fork's staging bucket: unregistered by definition,
# and every skill in it carries `metadata.internal: true`.
UNSHIPPED = ("misc", "in-progress", "deprecated", "in-development")

NOTE = (
    "Generated by scripts/generate-marketplace.py from .fork/catalog.yaml — do "
    "not hand-edit. This manifest exists solely so the skills.sh installer can "
    "group its picker; it is not an install route. This fork ships via "
    "skills.sh only (npx skills@latest add hugues-vnsgn/skills)."
)


def die(msg):
    print(f"generate-marketplace: {msg}", file=sys.stderr)
    sys.exit(1)


def load_catalog(repo):
    path = os.path.join(repo, ".fork", "catalog.yaml")
    try:
        with open(path, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except FileNotFoundError:
        die(f"{path} not found")
    except yaml.YAMLError as exc:
        die(f"{path} is not valid YAML: {exc}")
    if not isinstance(data, dict) or not isinstance(data.get("skills"), list):
        die(f"{path} must be a mapping with a `skills` list")
    return data


def group_name(domain):
    """`engineering` stays; a fork domain becomes `team-<domain>`."""
    return domain if domain in UPSTREAM_BUCKETS else f"team-{domain}"


def build(repo, catalog):
    domains = catalog.get("domains") or []
    if not domains:
        die("catalog.yaml must declare `domains`")

    errors = []
    by_group = {}
    for i, entry in enumerate(catalog["skills"]):
        where = entry.get("name") or f"skills[{i}]"
        domain, path = entry.get("domain"), entry.get("path")
        if not domain or not path:
            errors.append(f"{where}: missing `domain` or `path`")
            continue
        if domain not in domains:
            errors.append(f"{where}: domain `{domain}` not in `domains`")
            continue
        if domain in UNSHIPPED:
            continue
        # A group entry the installer cannot resolve silently drops the skill
        # from the picker, so prove the path before writing it.
        if not os.path.isfile(os.path.join(repo, path, "SKILL.md")):
            errors.append(f"{where}: no SKILL.md at {path}")
            continue
        by_group.setdefault(group_name(domain), []).append(f"./{path}")

    if errors:
        for err in errors:
            print(f"generate-marketplace: {err}", file=sys.stderr)
        sys.exit(1)
    if not by_group:
        die("no shipped skills — refusing to write an empty manifest")

    return {
        "name": "osxsystem-skills",
        "metadata": {"note": NOTE},
        "plugins": [
            {"name": name, "skills": sorted(by_group[name])}
            for name in sorted(by_group)
        ],
    }


def main():
    args = sys.argv[1:]
    check = "--check" in args
    positional = [a for a in args if not a.startswith("-")]
    repo = positional[0] if positional else "."
    unknown = [a for a in args if a.startswith("-") and a != "--check"]
    if unknown:
        die(f"unknown option(s): {' '.join(unknown)}")

    manifest = build(repo, load_catalog(repo))
    rendered = json.dumps(manifest, indent=2) + "\n"
    count = sum(len(p["skills"]) for p in manifest["plugins"])
    summary = f"{count} skills in {len(manifest['plugins'])} groups"

    target = os.path.join(repo, ".claude-plugin", "marketplace.json")
    current = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as fh:
            current = fh.read()

    if check:
        if current != rendered:
            die(
                ".claude-plugin/marketplace.json is stale — run "
                "`python3 scripts/generate-marketplace.py`"
            )
        print(f"marketplace.json is up to date ({summary})")
        return

    if current == rendered:
        print(f"marketplace.json unchanged ({summary})")
        return
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"marketplace.json written ({summary})")


if __name__ == "__main__":
    main()
